import { Josefin_Sans } from "next/font/google";
import Navbar from "./_component/navbar";

const josephine = Josefin_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={josephine.className}>
        {/* <Navbar /> */}
        {children}
      </body>
    </html>
  );
}
