import Profile from "@/asets/profile.png";
import flag from "@/asets/kenya.png";
export const TableData = [
  {
    flag: flag,
    Name: "Felix Adhiambo",
    Country: "Nairobi, Kenya",
    skill: "Photoshop, Content Creation, Video Editing, Google Analytics.",
    leve: "Professional",
    gender: "Male",
    portfolio: "www.felixadhiambo/profile.com",
    profileImage: Profile,
    profileTitle: "Digital Marketing Specialist",
  },
  {
    flag: flag,
    Name: "Felix Adhiambo",
    Country: "Nairobi, Kenya",
    skill: "Photoshop, Content Creation, Video Editing, Google Analytics.",
    leve: "Professional",
    gender: "Female",
    portfolio: "www.felixadhiambo/profile.com",
    profileImage: Profile,
    profileTitle: "Digital Marketing Specialist",
  },
  {
    flag: flag,
    Name: "Felix Adhiambo",
    Country: "Nairobi, Kenya",
    skill: "Photoshop, Content Creation, Video Editing, Google Analytics.",
    leve: "Professional",
    gender: "man",
    portfolio: "www.felixadhiambo/profile.com",
    profileImage: Profile,
    profileTitle: "Digital Marketing Specialist",
  },
  {
    flag: flag,
    Name: "Felix Adhiambo",
    Country: "Nairobi, Kenya",
    skill: "Photoshop, Content Creation, Video Editing, Google Analytics.",
    leve: "Professional",
    gender: "woman",
    portfolio: "www.felixadhiambo/profile.com",
    profileImage: Profile,
    profileTitle: "Digital Marketing Specialist",
  },
  {
    flag: flag,
    Name: "Felix Adhiambo",
    Country: "Nairobi, Kenya",
    skill: "Photoshop, Content Creation, Video Editing, Google Analytics.",
    leve: "Professional",
    gender: "womany",
    portfolio: "www.felixadhiambo/profile.com",
    profileImage: Profile,
    profileTitle: "Digital Marketing Specialist",
  },
];
