import Profile from "@/asets/profile.png";
import flag from "@/asets/kenya.png";
import Girl1 from "@/asets/boy5.jpg";
import Girl2 from "@/asets/girl4.jpg";
import Boy2 from "@/asets/boy2.jpeg";
import Boy1 from "@/asets/boy3.jpeg";
export const Talent = [
  {
    flag: flag,
    Name: "Alexi Kelvin",
    Country: "Nairobi, Kenya",
    skill: "Photoshop, Content Creation, Video Editing, Google Analytics.",
    leve: "Professional",
    gender: "Male",
    portfolio: "www.felixadhiambo/profile.com",
    profileImage: Girl2,
    profileTitle: "Digital Marketing Specialist",
  },
  {
    flag: flag,
    Name: "Chilaka Chilaka",
    Country: "Nairobi, Kenya",
    skill: "Photoshop, Content Creation, Video Editing, Google Analytics.",
    leve: "Professional",
    gender: "Female",
    portfolio: "www.felixadhiambo/profile.com",
    profileImage: Boy1,
    profileTitle: "Digital Marketing Specialist",
  },
  {
    flag: flag,
    Name: "Felix Adhiambo",
    Country: "Nairobi, Kenya",
    skill: "Photoshop, Content Creation, Video Editing, Google Analytics.",
    leve: "Professional",
    gender: "man",
    portfolio: "www.felixadhiambo/profile.com",
    profileImage: Profile,
    profileTitle: "Digital Marketing Specialist",
  },
  {
    flag: flag,
    Name: "Swazzy Somoto",
    Country: "Nairobi, Kenya",
    skill: "Photoshop, Content Creation, Video Editing, Google Analytics.",
    leve: "Professional",
    gender: "woman",
    portfolio: "www.felixadhiambo/profile.com",
    profileImage: Boy2,
    profileTitle: "Digital Marketing Specialist",
  },
  {
    flag: flag,
    Name: "Kathryn Filler",
    Country: "Nairobi, Kenya",
    skill: "Photoshop, Content Creation, Video Editing, Google Analytics.",
    leve: "Professional",
    gender: "womany",
    portfolio: "www.felixadhiambo/profile.com",
    profileImage: Girl1,
    profileTitle: "Digital Marketing Specialist",
  },
  {
    flag: flag,
    Name: "Felix Adhiambo",
    Country: "Nairobi, Kenya",
    skill: "Photoshop, Content Creation, Video Editing, Google Analytics.",
    leve: "Professional",
    gender: "womany",
    portfolio: "www.felixadhiambo/profile.com",
    profileImage: Boy1,
    profileTitle: "Digital Marketing Specialist",
  },
  {
    flag: flag,
    Name: "Felix Adhiambo",
    Country: "Nairobi, Kenya",
    skill: "Photoshop, Content Creation, Video Editing, Google Analytics.",
    leve: "Professional",
    gender: "womany",
    portfolio: "www.felixadhiambo/profile.com",
    profileImage: Profile,
    profileTitle: "Digital Marketing Specialist",
  },
];
