import { Inter, Josefin_Sans } from "next/font/google";
import SideBar from "./_components/sidebar";

const inter = Inter({ subsets: ["latin"] });
const josefin = Josefin_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={josefin.className}>
        <div className="flex gap-4">
          <SideBar />
          {children}
        </div>
      </body>
    </html>
  );
}
